import { Product, Coupon, StoreSettings, Order } from './types';

export const SAMPLE_IMAGE_PRESETS = [
  // DIGITAL PRODUCTS
  {
    title: '4K Cinema Video & Media Production',
    url: 'https://images.unsplash.com/photo-1574717024653-61fd2cf4d44d?auto=format&fit=crop&w=900&q=80',
    category: 'Content Creation',
  },
  {
    title: 'Creator Desk & Content Matrix Workspace',
    url: 'https://images.unsplash.com/photo-1517245386807-bb43f82c33c4?auto=format&fit=crop&w=900&q=80',
    category: 'Content Creation',
  },
  {
    title: 'Brand Identity Mockups & Typography Suite',
    url: 'https://images.unsplash.com/photo-1626785774573-4b799315345d?auto=format&fit=crop&w=900&q=80',
    category: 'Graphic Design',
  },
  {
    title: 'UI/UX Design System & Figma Wireframes',
    url: 'https://images.unsplash.com/photo-1581291518655-9523c932deb4?auto=format&fit=crop&w=900&q=80',
    category: 'Graphic Design',
  },
  {
    title: 'Agency Scale Funnels & Analytics OS',
    url: 'https://images.unsplash.com/photo-1460925895917-afdab827c52f?auto=format&fit=crop&w=900&q=80',
    category: 'Business & Marketing',
  },
  {
    title: 'Email Marketing & High-Converting Sequences',
    url: 'https://images.unsplash.com/photo-1563986768609-322da13575f3?auto=format&fit=crop&w=900&q=80',
    category: 'Email Marketing',
  },
  {
    title: 'Full-Stack Next.js Developer SaaS Boilerplate',
    url: 'https://images.unsplash.com/photo-1555066931-4365d14bab8c?auto=format&fit=crop&w=900&q=80',
    category: 'Software & WordPress',
  },
  {
    title: 'WordPress Power Pro Suite & Web Kits',
    url: 'https://images.unsplash.com/photo-1507238691740-187a5b1d37b8?auto=format&fit=crop&w=900&q=80',
    category: 'Software & WordPress',
  },
  {
    title: 'Cinematic Filmmaking Gear & 3D LUTs',
    url: 'https://images.unsplash.com/photo-1492691527719-9d1e07e534b4?auto=format&fit=crop&w=900&q=80',
    category: 'Video & Audio',
  },
  {
    title: 'Solopreneur Digital Wealth Blueprint',
    url: 'https://images.unsplash.com/photo-1522202176988-66273c2fd55f?auto=format&fit=crop&w=900&q=80',
    category: 'Courses & Education',
  },

  // AI RESOURCES
  {
    title: 'ChatGPT & Large Language Model Prompts Vault',
    url: 'https://images.unsplash.com/photo-1677442136019-21780efad99a?auto=format&fit=crop&w=900&q=80',
    category: 'ChatGPT Prompts',
  },
  {
    title: 'AI Automation & Autonomous Agents Hub',
    url: 'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?auto=format&fit=crop&w=900&q=80',
    category: 'AI Tools',
  },
  {
    title: 'AI Content Generation & Copywriting Engine',
    url: 'https://images.unsplash.com/photo-1682687220063-4742bd7fd538?auto=format&fit=crop&w=900&q=80',
    category: 'AI Content',
  },
  {
    title: 'Midjourney & AI Graphics Visual Vault',
    url: 'https://images.unsplash.com/photo-1634017839464-5c339ebe3cb4?auto=format&fit=crop&w=900&q=80',
    category: 'AI Graphics',
  },

  // TEMPLATES
  {
    title: 'Canva Modern Creator Templates Pack',
    url: 'https://images.unsplash.com/photo-1611162617474-5b21e879e113?auto=format&fit=crop&w=900&q=80',
    category: 'Canva',
  },
  {
    title: 'Photoshop PSD Product Mockups & Layers',
    url: 'https://images.unsplash.com/photo-1542744094-3a31f272c490?auto=format&fit=crop&w=900&q=80',
    category: 'Photoshop',
  },
  {
    title: 'Pitch Deck & PowerPoint Investor Slides',
    url: 'https://images.unsplash.com/photo-1557804506-669a67965ba0?auto=format&fit=crop&w=900&q=80',
    category: 'PowerPoint',
  },
  {
    title: 'Excel Financial Modeling & Automated Sheets',
    url: 'https://images.unsplash.com/photo-1460925895917-afdab827c52f?auto=format&fit=crop&w=900&q=80',
    category: 'Excel',
  },
  {
    title: 'WordPress High-Conversion Elementor Kits',
    url: 'https://images.unsplash.com/photo-1498050108023-c5249f4df085?auto=format&fit=crop&w=900&q=80',
    category: 'WordPress',
  },
  {
    title: 'Social Media Viral Carousels & Posts',
    url: 'https://images.unsplash.com/photo-1611162616305-c69b3fa7fbe0?auto=format&fit=crop&w=900&q=80',
    category: 'Social Media',
  },

  // PLR / MRR
  {
    title: 'PLR Written Content & Articles Vault',
    url: 'https://images.unsplash.com/photo-1455390582262-044cdead277a?auto=format&fit=crop&w=900&q=80',
    category: 'PLR Articles',
  },
  {
    title: 'Rebrandable PLR Ebooks & Guides',
    url: 'https://images.unsplash.com/photo-1544716278-ca5e3f4abd8c?auto=format&fit=crop&w=900&q=80',
    category: 'PLR Ebooks',
  },
  {
    title: 'MRR Resell Rights Planners & Journals',
    url: 'https://images.unsplash.com/photo-1506784365847-bbad939e9335?auto=format&fit=crop&w=900&q=80',
    category: 'PLR Templates',
  },
  {
    title: 'Digital Resell Products & Business Assets',
    url: 'https://images.unsplash.com/photo-1556742049-0a67c5574f73?auto=format&fit=crop&w=900&q=80',
    category: 'Resell Products',
  },
  {
    title: 'Legal Contracts & Agency Agreements',
    url: 'https://images.unsplash.com/photo-1450133064473-71024230f91b?auto=format&fit=crop&w=900&q=80',
    category: 'Business Resources',
  },

  // MEGA BUNDLES
  {
    title: 'Super Mega Bundle Creator Collection',
    url: 'https://images.unsplash.com/photo-1551836022-d5d88e9218df?auto=format&fit=crop&w=900&q=80',
    category: 'MEGA BUNDLES',
  },
];

export const INITIAL_PRODUCTS: Product[] = [
  // 1. DIGITAL PRODUCTS -> Content Creation
  {
    id: 'prod-cc-01',
    name: 'Ultimate Content Creator Mega Vault (5,000+ Assets)',
    slug: 'ultimate-content-creator-mega-vault',
    category: 'Content Creation',
    description: 'The master content bundle packed with 5,000+ viral Reels & Shorts templates, 4K kinetic typography clips, motion graphics hooks, YouTube thumbnail PSDs, sound FX, and ready-to-post vertical videos.',
    features: [
      '2,500+ Ready-to-edit Canva & Premiere Reels/Shorts templates',
      '800+ 4K Cinematic Background Loops & Textures',
      '1,200+ Sound Effects (Whooshes, Risers, Pop, Bass Drops)',
      '150+ High-CTR YouTube Thumbnail Templates (PSD & Canva)',
      'Commercial License & Lifetime Free Updates',
    ],
    regularPrice: 2499,
    salePrice: 199,
    badges: ['BESTSELLER', 'MEGA BUNDLE', '85% OFF'],
    deliveryLink: 'https://drive.google.com/drive/folders/content-creator-vault-instant-access',
    fileSize: '48.5 GB',
    fileFormat: 'Canva / Premiere / PSD / 4K MP4',
    rating: 4.9,
    reviewCount: 482,
    salesCount: 3240,
    mockupTheme: 'amber',
    imageUrl: 'https://images.unsplash.com/photo-1574717024653-61fd2cf4d44d?auto=format&fit=crop&w=900&q=80',
    metaKeywords: ['viral reels', 'shorts templates', 'content creator vault', 'youtube thumbnails', 'canva templates', 'video editing bundle'],
    isFeatured: true,
    isActive: true,
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'prod-cc-02',
    name: 'Viral Hooks, Scripts & Notion Content Engine',
    slug: 'viral-hooks-scripts-notion-engine',
    category: 'Content Creation',
    description: 'Over 1,000 battle-tested viral hooks, storytelling frameworks, 30-day content calendar templates, and complete Notion workspace for creators and agencies.',
    features: [
      '1,000+ Proven video hook formulas across 12 niches',
      'Full Notion Creator OS & Content Matrix Dashboard',
      'Script breakdown templates for TikTok, Reels, & YouTube',
      'Carousel design templates for LinkedIn & Instagram',
    ],
    regularPrice: 1499,
    salePrice: 149,
    badges: ['HOT DEAL', '70% OFF'],
    deliveryLink: 'https://drive.google.com/drive/folders/notion-creator-engine-access',
    fileSize: '2.4 GB',
    fileFormat: 'Notion Template / PDF / DOCX',
    rating: 4.8,
    reviewCount: 194,
    salesCount: 1420,
    mockupTheme: 'obsidian',
    imageUrl: 'https://images.unsplash.com/photo-1517245386807-bb43f82c33c4?auto=format&fit=crop&w=900&q=80',
    metaKeywords: ['viral hooks', 'notion content engine', 'tiktok scripts', 'instagram carousels', 'content calendar'],
    isActive: true,
    updatedAt: new Date().toISOString(),
  },

  // 2. DIGITAL PRODUCTS -> Graphic Design
  {
    id: 'prod-gd-01',
    name: 'Master Graphic Designer Suite (10,000+ Vector & PSD Assets)',
    slug: 'master-graphic-designer-suite',
    category: 'Graphic Design',
    description: 'Gigantic creative bundle containing premium branding mockups, geometric vector icons, typography posters, social media layout kits, Lightroom presets, and textures.',
    features: [
      '500+ High-Resolution Photorealistic Mockups (300 DPI, Smart Objects)',
      '3,000+ Vector Icons, Badges & Vintage Emblem illustrations',
      '1,500+ Premium Fonts & Editorial Typography Pairings',
      '50+ Complete Brand Identity Presentation Decks',
      'Full Commercial & Print-on-Demand License',
    ],
    regularPrice: 3999,
    salePrice: 249,
    badges: ['BESTSELLER', 'HOT SELL'],
    deliveryLink: 'https://mega.nz/folder/graphic-design-master-suite-cloud',
    fileSize: '62.0 GB',
    fileFormat: 'PSD / AI / EPS / OTF / SVG',
    rating: 5.0,
    reviewCount: 521,
    salesCount: 2980,
    mockupTheme: 'purple',
    imageUrl: 'https://images.unsplash.com/photo-1626785774573-4b799315345d?auto=format&fit=crop&w=900&q=80',
    metaKeywords: ['graphic design suite', 'photoshop mockups', 'vector icons', 'branding kit', 'fonts bundle'],
    isFeatured: true,
    isActive: true,
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'prod-gd-02',
    name: 'Ultra UI/UX Design System & Figma Wireframe Kit',
    slug: 'ultra-ui-ux-design-system-figma-kit',
    category: 'Graphic Design',
    description: 'Enterprise Figma design system with 2,400+ auto-layout components, WCAG accessible color palettes, responsive web wireframes, and mobile app screens.',
    features: [
      '2,400+ Auto-Layout 5.0 Figma UI components',
      '60+ Pre-built Responsive Web & Dashboard Layouts',
      'Design token library with light & dark mode variants',
      'Interactive prototype states & micro-interactions',
    ],
    regularPrice: 2999,
    salePrice: 199,
    badges: ['LIMITED OFFER'],
    deliveryLink: 'https://drive.google.com/drive/folders/figma-ui-system-enterprise',
    fileSize: '1.8 GB',
    fileFormat: 'Figma (.fig) / Tokens JSON',
    rating: 4.9,
    reviewCount: 284,
    salesCount: 1650,
    mockupTheme: 'cyan',
    imageUrl: 'https://images.unsplash.com/photo-1581291518655-9523c932deb4?auto=format&fit=crop&w=900&q=80',
    metaKeywords: ['figma design system', 'ui ux kit', 'wireframe kit', 'dashboard templates', 'figma components'],
    isActive: true,
    updatedAt: new Date().toISOString(),
  },

  // 3. DIGITAL PRODUCTS -> Business & Marketing
  {
    id: 'prod-bm-01',
    name: 'Agency Scale In A Box: Business & Funnel OS',
    slug: 'agency-scale-business-funnel-os',
    category: 'Business & Marketing',
    description: 'Complete operating system for digital agencies and freelancers. Includes high-converting proposal templates, client contracts, SOPs, pitch decks, and ad swipe files.',
    features: [
      'Legally vetted client service agreements & NDAs',
      'High-converting pitch decks (Keynote, PowerPoint, Google Slides)',
      '30+ Standard Operating Procedures (SOPs) for team delegation',
      'Meta & Google Ads high-ROI swipe files with $2M+ spend data',
      'Client onboarding Notion portal & project tracker',
    ],
    regularPrice: 3499,
    salePrice: 249,
    badges: ['HOT DEAL', 'BESTSELLER'],
    deliveryLink: 'https://drive.google.com/drive/folders/agency-scale-in-a-box-bundle',
    fileSize: '4.8 GB',
    fileFormat: 'Notion / PPTX / PDF / DOCX',
    rating: 4.9,
    reviewCount: 310,
    salesCount: 2150,
    mockupTheme: 'emerald',
    imageUrl: 'https://images.unsplash.com/photo-1460925895917-afdab827c52f?auto=format&fit=crop&w=900&q=80',
    metaKeywords: ['agency operating system', 'client proposal templates', 'marketing swipe file', 'business contracts', 'freelance os'],
    isFeatured: true,
    isActive: true,
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'prod-bm-02',
    name: 'E-Commerce Growth Playbook & 100+ Ad Creatives',
    slug: 'ecommerce-growth-playbook-ad-creatives',
    category: 'Business & Marketing',
    description: 'The proven Shopify and D2C scaling blueprint featuring TikTok & Meta ad creatives, product landing page wireframes, and retention email flows.',
    features: [
      '100+ High-converting Canva e-commerce static and video ads',
      'Landing page copy frameworks with 4%+ conversion benchmarks',
      'Customer acquisition cost (CAC) reduction checklist',
      'Influencer outreach scripts & contract templates',
    ],
    regularPrice: 1999,
    salePrice: 169,
    badges: ['70% OFF'],
    deliveryLink: 'https://drive.google.com/drive/folders/ecommerce-scaling-kit-vault',
    fileSize: '5.2 GB',
    fileFormat: 'Canva / PSD / PDF Guide',
    rating: 4.8,
    reviewCount: 178,
    salesCount: 1190,
    mockupTheme: 'amber',
    imageUrl: 'https://images.unsplash.com/photo-1556742049-0a67c5574f73?auto=format&fit=crop&w=900&q=80',
    metaKeywords: ['ecommerce playbook', 'ad creatives bundle', 'shopify templates', 'ugc ad scripts', 'conversion copywriting'],
    isActive: true,
    updatedAt: new Date().toISOString(),
  },

  // 4. DIGITAL PRODUCTS -> Email Marketing
  {
    id: 'prod-em-01',
    name: 'Email Marketing Mega Bundle (1,200+ High-Conversion Sequences)',
    slug: 'email-marketing-mega-bundle-sequences',
    category: 'Email Marketing',
    description: 'A master library of battle-tested email campaigns: welcome sequences, abandoned cart triggers, flash sale sequences, webinar promos, and newsletter retention flows.',
    features: [
      '1,200+ Plug-and-play email swipe files across 25 industries',
      'HTML responsive email templates compatible with Mailchimp, Klaviyo, Brevo',
      'Subject line generator with 45%+ average open-rate formulas',
      'Automated drip sequence blueprints for SaaS, Courses, & E-commerce',
    ],
    regularPrice: 2299,
    salePrice: 149,
    badges: ['FLASH SALE', '80% OFF'],
    deliveryLink: 'https://drive.google.com/drive/folders/email-marketing-mega-vault',
    fileSize: '1.2 GB',
    fileFormat: 'HTML / DOCX / Notion / JSON',
    rating: 4.9,
    reviewCount: 389,
    salesCount: 2640,
    mockupTheme: 'cyan',
    imageUrl: 'https://images.unsplash.com/photo-1563986768609-322da13575f3?auto=format&fit=crop&w=900&q=80',
    isFeatured: true,
    isActive: true,
    updatedAt: new Date().toISOString(),
  },

  // 5. DIGITAL PRODUCTS -> Software & WordPress
  {
    id: 'prod-sw-01',
    name: 'Full-Stack Developer Toolkit & Next.js SaaS Boilerplates',
    slug: 'fullstack-developer-saas-boilerplates',
    category: 'Software & WordPress',
    description: 'Production-ready Next.js 15, Tailwind CSS, TypeScript boilerplates with pre-configured Stripe payments, authentication, database schemas, and AI integrations.',
    features: [
      'Complete Next.js App Router full-stack SaaS starter',
      'Integrated authentication, payment webhooks & PostgreSQL setup',
      'Clean modular architecture with 80+ pre-built React components',
      'Includes private GitHub repo access & continuous codebase updates',
    ],
    regularPrice: 4999,
    salePrice: 299,
    badges: ['BESTSELLER', 'HOT DEAL'],
    deliveryLink: 'https://drive.google.com/drive/folders/fullstack-developer-saas-vault',
    fileSize: '850 MB',
    fileFormat: 'TypeScript / Next.js / Tailwind / SQL',
    rating: 5.0,
    reviewCount: 412,
    salesCount: 1980,
    mockupTheme: 'obsidian',
    imageUrl: 'https://images.unsplash.com/photo-1555066931-4365d14bab8c?auto=format&fit=crop&w=900&q=80',
    isFeatured: true,
    isActive: true,
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'prod-sw-02',
    name: 'WordPress Power Pro Suite & 150+ Premium Web Kits',
    slug: 'wordpress-power-pro-suite-web-kits',
    category: 'Software & WordPress',
    description: 'Collection of clean, lightning-fast WordPress Elementor & Gutenberg kits, landing page designs, and utility PHP code snippets tested for maximum speed and security.',
    features: [
      '150+ Responsive Elementor Pro & Gutenberg complete website templates',
      'Performance optimization presets (95+ Google PageSpeed score)',
      'WooCommerce high-conversion product page layouts',
      'Clean clean PHP snippets to replace bulky third-party plugins',
    ],
    regularPrice: 2799,
    salePrice: 199,
    badges: ['LIMITED OFFER'],
    deliveryLink: 'https://mega.nz/folder/wordpress-power-pro-suite-cloud',
    fileSize: '14.2 GB',
    fileFormat: 'JSON / Elementor Kit / XML / PHP',
    rating: 4.8,
    reviewCount: 205,
    salesCount: 1340,
    mockupTheme: 'purple',
    imageUrl: 'https://images.unsplash.com/photo-1507238691740-187a5b1d37b8?auto=format&fit=crop&w=900&q=80',
    isActive: true,
    updatedAt: new Date().toISOString(),
  },

  // 6. DIGITAL PRODUCTS -> Video & Audio
  {
    id: 'prod-va-01',
    name: 'Cinematic Video Creator Bundle (3D LUTs, SFX & 4K Overlays)',
    slug: 'cinematic-video-creator-bundle-luts-sfx',
    category: 'Video & Audio',
    description: 'The ultimate video editor suite used by top YouTubers and filmmakers: 250+ Hollywood LUTs, film grain overlays, VHS textures, sound effects, and title templates.',
    features: [
      '250+ Professional Cinematic LUTs (Sony S-Log, Canon, Blackmagic, iPhone)',
      '1,500+ High-definition Foley & sound design audio tracks (WAV 24-bit)',
      '4K Real Film Burn, Light Leak & Dust Overlays',
      'Compatible with Premiere Pro, DaVinci Resolve, Final Cut & CapCut',
    ],
    regularPrice: 2999,
    salePrice: 199,
    badges: ['BESTSELLER', 'HOT DEAL'],
    deliveryLink: 'https://drive.google.com/drive/folders/cinematic-video-creator-vault',
    fileSize: '36.8 GB',
    fileFormat: '.cube / 24-bit WAV / 4K ProRes MP4',
    rating: 4.9,
    reviewCount: 367,
    salesCount: 2210,
    mockupTheme: 'rose',
    imageUrl: 'https://images.unsplash.com/photo-1492691527719-9d1e07e534b4?auto=format&fit=crop&w=900&q=80',
    isFeatured: true,
    isActive: true,
    updatedAt: new Date().toISOString(),
  },

  // 7. DIGITAL PRODUCTS -> Courses & Education
  {
    id: 'prod-ed-01',
    name: 'Digital Wealth & Solopreneur Blueprint (Complete Masterclass)',
    slug: 'digital-wealth-solopreneur-blueprint-masterclass',
    category: 'Courses & Education',
    description: 'Step-by-step video masterclass and action workbooks explaining how to build, launch, and automate digital product storefronts generating $10k/month passive revenue.',
    features: [
      '24 In-depth video modules with transcriptions and exercise sheets',
      'Product ideation, niche validation, and pricing frameworks',
      'Organic traffic generation strategy for Pinterest, YouTube & TikTok',
      'Automated email marketing sales funnels breakdown',
    ],
    regularPrice: 3999,
    salePrice: 249,
    badges: ['BESTSELLER', 'NEW RELEASE'],
    deliveryLink: 'https://drive.google.com/drive/folders/digital-wealth-masterclass-hd',
    fileSize: '18.4 GB',
    fileFormat: '1080p MP4 / PDF Workbook / Notion OS',
    rating: 5.0,
    reviewCount: 442,
    salesCount: 1890,
    mockupTheme: 'emerald',
    imageUrl: 'https://images.unsplash.com/photo-1522202176988-66273c2fd55f?auto=format&fit=crop&w=900&q=80',
    isFeatured: true,
    isActive: true,
    updatedAt: new Date().toISOString(),
  },

  // 8. AI RESOURCES -> ChatGPT Prompts
  {
    id: 'prod-ai-01',
    name: '15,000+ Ultimate ChatGPT & Claude AI Prompts Mega Vault',
    slug: '15000-chatgpt-claude-prompts-mega-vault',
    category: 'ChatGPT Prompts',
    description: 'The world\'s most comprehensive ChatGPT, Claude & Gemini prompt collection. Covers high-converting sales copy, SEO articles, Python/Next.js code generation, marketing funnels, and prompt engineering frameworks.',
    features: [
      '15,000+ Categorized high-yield prompts with variables and output controls',
      'Master prompt chains for copywriting, email campaigns, and SEO',
      'Code generation & debugging prompts for developers',
      'Searchable Notion & Excel prompt database with lifetime updates',
    ],
    regularPrice: 2199,
    salePrice: 149,
    badges: ['BESTSELLER', 'HOT DEAL', '85% OFF'],
    deliveryLink: 'https://drive.google.com/drive/folders/chatgpt-master-prompt-vault-access',
    fileSize: '1.5 GB',
    fileFormat: 'Notion Database / Excel / PDF / JSON',
    rating: 4.95,
    reviewCount: 612,
    salesCount: 4120,
    mockupTheme: 'cyan',
    imageUrl: 'https://images.unsplash.com/photo-1677442136019-21780efad99a?auto=format&fit=crop&w=900&q=80',
    isFeatured: true,
    isActive: true,
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'prod-ai-02',
    name: 'Midjourney & AI Art Photorealism Prompt Bible',
    slug: 'midjourney-ai-art-photorealism-prompt-bible',
    category: 'ChatGPT Prompts',
    description: '3,000+ precise visual prompts for Midjourney v6, DALL-E 3, and Stable Diffusion. Produce photorealistic studio portraits, 3D product renders, futuristic UI, and logo concepts effortlessly.',
    features: [
      '3,000+ Tested Midjourney v6 prompts with visual reference cards',
      'Lighting, camera lenses, aspect ratios, and stylize parameter guides',
      'Ready-to-use aesthetic style cheat-sheets',
      'Commercial usage guide for print-on-demand and stock marketplaces',
    ],
    regularPrice: 1899,
    salePrice: 129,
    badges: ['HOT DEAL', '70% OFF'],
    deliveryLink: 'https://drive.google.com/drive/folders/midjourney-art-prompt-bible',
    fileSize: '3.2 GB',
    fileFormat: 'PDF Guide / Notion / High-Res PNG Samples',
    rating: 4.9,
    reviewCount: 341,
    salesCount: 2310,
    mockupTheme: 'purple',
    imageUrl: 'https://images.unsplash.com/photo-1634017839464-5c339ebe3cb4?auto=format&fit=crop&w=900&q=80',
    isActive: true,
    updatedAt: new Date().toISOString(),
  },

  // 9. AI RESOURCES -> AI Tools
  {
    id: 'prod-ai-03',
    name: 'Autonomous AI Agents & Zapier Automation Blueprint Suite',
    slug: 'autonomous-ai-agents-zapier-automation-blueprints',
    category: 'AI Tools',
    description: 'Pre-built Make.com & Zapier JSON automation scenarios that connect OpenAI, Google Gemini, and Claude directly to your CRM, Google Sheets, Gmail, and Slack.',
    features: [
      '25+ Ready-to-import Make.com & Zapier JSON automation blueprints',
      'Autonomous lead qualification and CRM reply bot',
      'Automated social media repurposing and scheduling agent',
      'Complete video setup walkthrough & troubleshooting guides',
    ],
    regularPrice: 3299,
    salePrice: 249,
    badges: ['NEW RELEASE', 'LIMITED OFFER'],
    deliveryLink: 'https://drive.google.com/drive/folders/ai-agents-automation-blueprints',
    fileSize: '2.1 GB',
    fileFormat: 'JSON Blueprints / Video Guides / Diagrams',
    rating: 4.88,
    reviewCount: 198,
    salesCount: 1470,
    mockupTheme: 'obsidian',
    imageUrl: 'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?auto=format&fit=crop&w=900&q=80',
    isActive: true,
    updatedAt: new Date().toISOString(),
  },

  // 10. AI RESOURCES -> AI Content
  {
    id: 'prod-ai-04',
    name: 'AI Niche Blog & High-Volume SEO Content Empire System',
    slug: 'ai-niche-blog-high-volume-seo-content-system',
    category: 'AI Content',
    description: 'The proven framework to generate high-ranking, human-like SEO articles using AI that pass AI detectors and generate affiliate revenue.',
    features: [
      'Custom GPT prompt chains for 2,500+ word structured articles',
      'Schema markup, internal linking, and meta tag prompt system',
      '50 High-CPC niche keyword research clusters included',
      'Humanizer editing checklist to guarantee EEAT compliance',
    ],
    regularPrice: 2499,
    salePrice: 179,
    badges: ['FLASH SALE'],
    deliveryLink: 'https://drive.google.com/drive/folders/ai-seo-content-empire-system',
    fileSize: '1.4 GB',
    fileFormat: 'Notion OS / Google Docs / Video Guide',
    rating: 4.85,
    reviewCount: 220,
    salesCount: 1620,
    mockupTheme: 'amber',
    imageUrl: 'https://images.unsplash.com/photo-1682687220063-4742bd7fd538?auto=format&fit=crop&w=900&q=80',
    isActive: true,
    updatedAt: new Date().toISOString(),
  },

  // 11. AI RESOURCES -> AI Graphics
  {
    id: 'prod-ai-05',
    name: '5,000+ 8K Ultra-Realistic AI Textures & 3D Backgrounds',
    slug: '5000-8k-ultra-realistic-ai-textures-backgrounds',
    category: 'AI Graphics',
    description: 'Vast collection of 8K seamless textures: cyberpunk neon, luxury marble, iridescent glass, futuristic holographic surfaces, and botanical environments.',
    features: [
      '5,000+ 8K resolution textures and abstract wallpapers',
      'Seamless tileable patterns (PNG & JPG, 300 DPI)',
      'Optimized for web hero banners, posters, apparel, and 3D scenes',
      'Full unrestricted commercial license',
    ],
    regularPrice: 2799,
    salePrice: 199,
    badges: ['HOT DEAL', 'MEGA BUNDLE'],
    deliveryLink: 'https://mega.nz/folder/ai-graphics-textures-8k-cloud',
    fileSize: '32.0 GB',
    fileFormat: '8K PNG / JPG / TIFF',
    rating: 4.92,
    reviewCount: 312,
    salesCount: 2180,
    mockupTheme: 'rose',
    imageUrl: 'https://images.unsplash.com/photo-1634017839464-5c339ebe3cb4?auto=format&fit=crop&w=900&q=80',
    isActive: true,
    updatedAt: new Date().toISOString(),
  },

  // 12. TEMPLATES -> Canva
  {
    id: 'prod-tmpl-01',
    name: '3,500+ Ultimate All-In-One Canva Editable Templates Kit',
    slug: '3500-ultimate-canva-editable-templates-kit',
    category: 'Canva',
    description: 'The definitive Canva kit: modern Instagram posts, carousels, Pinterest pins, YouTube thumbnails, ebook covers, event flyers, and client invoices ready to edit in 1 click.',
    features: [
      '3,500+ Clean, fully editable Canva template direct links',
      'Organized into 30+ business, wellness, tech, and coaching niches',
      'One-click color palette and font swapping supported',
      'Lifetime updates with new seasonal design drops',
    ],
    regularPrice: 2999,
    salePrice: 199,
    badges: ['BESTSELLER', 'HOT DEAL', '80% OFF'],
    deliveryLink: 'https://drive.google.com/drive/folders/canva-all-in-one-templates-vault',
    fileSize: '4.5 GB',
    fileFormat: 'Canva Share Links / PDF Quick Access',
    rating: 4.96,
    reviewCount: 780,
    salesCount: 5290,
    mockupTheme: 'cyan',
    imageUrl: 'https://images.unsplash.com/photo-1611162617474-5b21e879e113?auto=format&fit=crop&w=900&q=80',
    isFeatured: true,
    isActive: true,
    updatedAt: new Date().toISOString(),
  },

  // 13. TEMPLATES -> Photoshop
  {
    id: 'prod-tmpl-02',
    name: '750+ Ultra-High Res Photorealistic Photoshop Mockups',
    slug: '750-photorealistic-photoshop-mockups-smart-objects',
    category: 'Photoshop',
    description: 'Professional PSD mockups with smart objects for apparel, branding stationery, tech devices (iPhone 16, MacBook Pro), packaging boxes, and cosmetics.',
    features: [
      '750+ High-resolution PSDs (4000x3000px, 300 DPI)',
      'Organized Smart Objects for instant 5-second paste & save',
      'Separated shadows, reflections, and changeable backgrounds',
      'Ideal for Behance, Dribbble, and e-commerce product listings',
    ],
    regularPrice: 3499,
    salePrice: 249,
    badges: ['BESTSELLER', 'LIMITED OFFER'],
    deliveryLink: 'https://mega.nz/folder/photoshop-pro-mockups-vault',
    fileSize: '42.0 GB',
    fileFormat: 'Photoshop PSD / Smart Objects',
    rating: 4.94,
    reviewCount: 429,
    salesCount: 2890,
    mockupTheme: 'obsidian',
    imageUrl: 'https://images.unsplash.com/photo-1542744094-3a31f272c490?auto=format&fit=crop&w=900&q=80',
    isActive: true,
    updatedAt: new Date().toISOString(),
  },

  // 14. TEMPLATES -> PowerPoint
  {
    id: 'prod-tmpl-03',
    name: 'PitchDeck Pro: 1,500+ Modern PowerPoint Investor Slides',
    slug: 'pitchdeck-pro-powerpoint-investor-slides',
    category: 'PowerPoint',
    description: 'Venture-backed pitch deck templates with 1,500+ slides, market sizing diagrams, revenue models, financial charts, and clean executive layouts.',
    features: [
      '1,500+ Unique slide layouts in 16:9 widescreen format',
      'Fully editable vector charts, maps, and icon sets',
      'Light and Dark mode master presentation themes',
      'Includes PowerPoint (.pptx), Google Slides, and Keynote files',
    ],
    regularPrice: 2499,
    salePrice: 179,
    badges: ['HOT DEAL'],
    deliveryLink: 'https://drive.google.com/drive/folders/pitchdeck-pro-powerpoint-vault',
    fileSize: '2.8 GB',
    fileFormat: 'PPTX / Google Slides / Keynote',
    rating: 4.88,
    reviewCount: 295,
    salesCount: 1940,
    mockupTheme: 'amber',
    imageUrl: 'https://images.unsplash.com/photo-1557804506-669a67965ba0?auto=format&fit=crop&w=900&q=80',
    isActive: true,
    updatedAt: new Date().toISOString(),
  },

  // 15. TEMPLATES -> Excel
  {
    id: 'prod-tmpl-04',
    name: 'Automated Financial Modeling & P&L Business Excel OS',
    slug: 'automated-financial-business-excel-os',
    category: 'Excel',
    description: 'Automated Excel and Google Sheets dashboards: automatic cash flow calculation, P&L statements, inventory valuation, and sales commission trackers.',
    features: [
      'Automated financial model with dynamic formulas and zero coding needed',
      'Visual KPIs, interactive slicers, and revenue forecasting charts',
      'Compatible with Microsoft Excel 2019/365 and Google Sheets',
      'Pre-loaded dummy sample data and detailed video instructions',
    ],
    regularPrice: 1999,
    salePrice: 149,
    badges: ['NEW RELEASE', '70% OFF'],
    deliveryLink: 'https://drive.google.com/drive/folders/financial-excel-os-vault',
    fileSize: '650 MB',
    fileFormat: 'XLSX / Google Sheets Direct Copy',
    rating: 4.9,
    reviewCount: 260,
    salesCount: 1720,
    mockupTheme: 'emerald',
    imageUrl: 'https://images.unsplash.com/photo-1460925895917-afdab827c52f?auto=format&fit=crop&w=900&q=80',
    isActive: true,
    updatedAt: new Date().toISOString(),
  },

  // 16. TEMPLATES -> WordPress
  {
    id: 'prod-tmpl-05',
    name: 'WordPress Ultra: 80+ Elementor Pro & Gutenberg Full Sites',
    slug: 'wordpress-ultra-elementor-gutenberg-full-sites',
    category: 'WordPress',
    description: 'Turnkey full website template kits for agencies, SaaS, gyms, doctors, restaurants, real estate, and portfolio artists.',
    features: [
      '80+ Complete multi-page site kits (Home, About, Services, Contact, Blog)',
      '100% Mobile responsive and optimized for ultra-fast load times',
      'One-click template import without writing CSS or PHP',
      'Includes header and footer builder presets',
    ],
    regularPrice: 3499,
    salePrice: 229,
    badges: ['LIMITED OFFER'],
    deliveryLink: 'https://mega.nz/folder/wordpress-elementor-kits-vault',
    fileSize: '16.5 GB',
    fileFormat: 'Elementor Kit JSON / XML',
    rating: 4.87,
    reviewCount: 210,
    salesCount: 1530,
    mockupTheme: 'purple',
    imageUrl: 'https://images.unsplash.com/photo-1498050108023-c5249f4df085?auto=format&fit=crop&w=900&q=80',
    isActive: true,
    updatedAt: new Date().toISOString(),
  },

  // 17. TEMPLATES -> Social Media
  {
    id: 'prod-tmpl-06',
    name: '2,500+ Viral Instagram & TikTok Carousels Engagement Kit',
    slug: '2500-viral-social-media-engagement-kit',
    category: 'Social Media',
    description: 'Designed specifically to boost saves, shares, and comments. High-performing psychological storytelling slides for Instagram, LinkedIn, and Threads.',
    features: [
      '2,500+ Seamless carousel slides & single-post templates',
      'Tested layouts in business, crypto, motivation, fitness, & real estate',
      'Includes viral quote graphics and tweet-style screenshot frames',
      'Canva and PSD format with commercial rights included',
    ],
    regularPrice: 2299,
    salePrice: 149,
    badges: ['FLASH SALE', '80% OFF'],
    deliveryLink: 'https://drive.google.com/drive/folders/social-media-engagement-vault',
    fileSize: '3.6 GB',
    fileFormat: 'Canva / PSD / PNG',
    rating: 4.93,
    reviewCount: 512,
    salesCount: 3650,
    mockupTheme: 'rose',
    imageUrl: 'https://images.unsplash.com/photo-1611162616305-c69b3fa7fbe0?auto=format&fit=crop&w=900&q=80',
    isActive: true,
    updatedAt: new Date().toISOString(),
  },

  // 18. PLR / MRR -> PLR Articles
  {
    id: 'prod-plr-01',
    name: '10,000+ Evergreen High-Authority PLR Articles & Content Vault',
    slug: '10000-evergreen-plr-articles-vault',
    category: 'PLR Articles',
    description: 'Massive archive of well-researched, editable articles with full Private Label Rights (PLR). Rebrand, publish under your name, or spin into newsletter editions.',
    features: [
      '10,000+ Full-length articles spanning 40+ profitable niches',
      'Clean TXT, DOCX, and PDF formats for rapid copying',
      'Full unrestricted PLR license: rebrand, resell, or distribute',
      'Includes headline variations and meta descriptions for each topic',
    ],
    regularPrice: 2499,
    salePrice: 169,
    badges: ['BESTSELLER', 'HOT DEAL'],
    deliveryLink: 'https://drive.google.com/drive/folders/plr-articles-mega-archive',
    fileSize: '2.9 GB',
    fileFormat: 'DOCX / TXT / PDF',
    rating: 4.88,
    reviewCount: 320,
    salesCount: 2410,
    mockupTheme: 'cyan',
    imageUrl: 'https://images.unsplash.com/photo-1455390582262-044cdead277a?auto=format&fit=crop&w=900&q=80',
    isActive: true,
    updatedAt: new Date().toISOString(),
  },

  // 19. PLR / MRR -> PLR Ebooks
  {
    id: 'prod-plr-02',
    name: '60+ Rebrandable PLR Ebooks with Canva Covers & Source Files',
    slug: '60-rebrandable-plr-ebooks-canva-covers',
    category: 'PLR Ebooks',
    description: 'High-quality digital books ready to sell in minutes. Each ebook includes editable Canva 3D cover mockups, Word (.docx) source files, and ready-to-sell landing copy.',
    features: [
      '60 Complete ebooks on digital marketing, AI, mindset, and finance',
      'Editable Canva source cover designs (change titles and author name in 1 click)',
      'Sales page copy and email announcement sequences included',
      'Private Label Rights (PLR) license included',
    ],
    regularPrice: 3299,
    salePrice: 229,
    badges: ['BESTSELLER', 'HOT DEAL'],
    deliveryLink: 'https://drive.google.com/drive/folders/plr-ebooks-rebrandable-vault',
    fileSize: '5.8 GB',
    fileFormat: 'DOCX / PDF / Canva Covers',
    rating: 4.95,
    reviewCount: 418,
    salesCount: 3180,
    mockupTheme: 'amber',
    imageUrl: 'https://images.unsplash.com/photo-1544716278-ca5e3f4abd8c?auto=format&fit=crop&w=900&q=80',
    isFeatured: true,
    isActive: true,
    updatedAt: new Date().toISOString(),
  },

  // 20. PLR / MRR -> PLR Templates
  {
    id: 'prod-plr-03',
    name: 'Master Resell Rights (MRR) Digital Planners & Journals Pack',
    slug: 'mrr-digital-planners-journals-bundle',
    category: 'PLR Templates',
    description: 'Hyperlinked digital planners for GoodNotes, Notability, and printable daily habits journals with 100% Master Resell Rights (MRR). Keep 100% of every sale.',
    features: [
      '15 Hyperlinked 365-day digital planners with index tabs',
      '25 Printable daily gratitude, fitness, and finance journals',
      'Full Master Resell Rights certificate included',
      'Ready-to-upload Etsy & Shopify listing mockups included',
    ],
    regularPrice: 2699,
    salePrice: 189,
    badges: ['HOT DEAL', 'LIMITED OFFER'],
    deliveryLink: 'https://drive.google.com/drive/folders/mrr-digital-planners-vault',
    fileSize: '4.2 GB',
    fileFormat: 'PDF Hyperlinked / Canva / GoodNotes',
    rating: 4.91,
    reviewCount: 380,
    salesCount: 2750,
    mockupTheme: 'rose',
    imageUrl: 'https://images.unsplash.com/photo-1506784365847-bbad939e9335?auto=format&fit=crop&w=900&q=80',
    isActive: true,
    updatedAt: new Date().toISOString(),
  },

  // 21. PLR / MRR -> Resell Products
  {
    id: 'prod-plr-04',
    name: 'Turnkey Digital Store: 100+ Ready-to-Resell Digital Products',
    slug: 'turnkey-digital-store-100-resell-products',
    category: 'Resell Products',
    description: 'Start an online digital store instantly. Over 100 high-converting software, guides, audio packs, and graphics with complete commercial resale rights.',
    features: [
      '100+ Standalone digital products with commercial resell licenses',
      'Pre-written product descriptions, features, and pricing tags',
      'High-resolution marketing graphics & 3D box mockups',
      'Step-by-step setup guide to launch on Shopify, Gumroad or Stan Store',
    ],
    regularPrice: 4999,
    salePrice: 299,
    badges: ['MEGA BUNDLE', 'HOT SELL', '85% OFF'],
    deliveryLink: 'https://mega.nz/folder/turnkey-resell-store-assets',
    fileSize: '28.5 GB',
    fileFormat: 'ZIP Packages / PDF / PSD Mockups',
    rating: 4.97,
    reviewCount: 560,
    salesCount: 3890,
    mockupTheme: 'emerald',
    imageUrl: 'https://images.unsplash.com/photo-1556742049-0a67c5574f73?auto=format&fit=crop&w=900&q=80',
    isFeatured: true,
    isActive: true,
    updatedAt: new Date().toISOString(),
  },

  // 22. PLR / MRR -> Business Resources
  {
    id: 'prod-plr-05',
    name: 'Legal Contracts, Freelance Agreements & Agency SOPs (MRR)',
    slug: 'legal-contracts-freelance-agreements-sops-mrr',
    category: 'Business Resources',
    description: 'Attorney-drafted contract templates: website development agreements, social media management retainers, NDAs, affiliate terms, and client intake SOPs.',
    features: [
      '35+ Essential business and freelance contract templates',
      'Drafted in plain English with fill-in-the-blank brackets',
      'Includes Notion agency operating dashboard & onboarding portal',
      'Full MRR/PLR rights to rebrand and resell as your own product',
    ],
    regularPrice: 2499,
    salePrice: 169,
    badges: ['NEW RELEASE'],
    deliveryLink: 'https://drive.google.com/drive/folders/business-legal-contracts-vault',
    fileSize: '1.1 GB',
    fileFormat: 'DOCX / PDF / Notion Template',
    rating: 4.89,
    reviewCount: 230,
    salesCount: 1680,
    mockupTheme: 'obsidian',
    imageUrl: 'https://images.unsplash.com/photo-1450133064473-71024230f91b?auto=format&fit=crop&w=900&q=80',
    isActive: true,
    updatedAt: new Date().toISOString(),
  },

  // 23. MEGA BUNDLES
  {
    id: 'prod-mb-01',
    name: '100-in-1 Master Creator & Solopreneur Ultimate Lifetime Super Bundle',
    slug: '100-in-1-master-creator-ultimate-lifetime-bundle',
    category: 'MEGA BUNDLES',
    description: 'The definitive all-in-one package: 100+ complete bundles spanning content creation, AI tools, templates, video/audio production, and resell rights products.',
    features: [
      'Includes every single top-rated resource across our entire platform',
      'Over 75,000+ files and 200+ GB of premium cloud storage assets',
      'Master commercial and resell rights included',
      'Lifetime cloud access with free quarterly library expansions',
    ],
    regularPrice: 9999,
    salePrice: 499,
    badges: ['BESTSELLER', 'MEGA BUNDLE', '90% OFF'],
    deliveryLink: 'https://mega.nz/folder/master-creator-super-bundle-cloud',
    fileSize: '185.0 GB',
    fileFormat: 'Canva / PSD / Premiere / Notion / PDF / Code',
    rating: 5.0,
    reviewCount: 940,
    salesCount: 6890,
    mockupTheme: 'amber',
    imageUrl: 'https://images.unsplash.com/photo-1551836022-d5d88e9218df?auto=format&fit=crop&w=900&q=80',
    isFeatured: true,
    isActive: true,
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'prod-mb-02',
    name: 'The Everything Developer & Designer Superpack (50,000+ Assets)',
    slug: 'everything-developer-designer-superpack',
    category: 'MEGA BUNDLES',
    description: 'Gigantic suite of SaaS boilerplates, UI kits, 3D icons, vector illustrations, font families, and code snippets.',
    features: [
      '50,000+ Curated vector assets, 3D renders, and UI elements',
      '12 Next.js and React full-stack boilerplate projects',
      'Commercial license for client client and SaaS projects',
      'High-speed cloud download mirrors with 99.9% uptime',
    ],
    regularPrice: 7999,
    salePrice: 399,
    badges: ['HOT DEAL', 'MEGA BUNDLE'],
    deliveryLink: 'https://drive.google.com/drive/folders/developer-designer-superpack-vip',
    fileSize: '95.0 GB',
    fileFormat: 'PSD / AI / Figma / TypeScript / 3D OBJ',
    rating: 4.98,
    reviewCount: 650,
    salesCount: 4520,
    mockupTheme: 'purple',
    imageUrl: 'https://images.unsplash.com/photo-1555066931-4365d14bab8c?auto=format&fit=crop&w=900&q=80',
    isFeatured: true,
    isActive: true,
    updatedAt: new Date().toISOString(),
  },
];

export const INITIAL_COUPONS: Coupon[] = [
  {
    id: 'coup-01',
    code: 'CREATOR70',
    discountPercentage: 20,
    minSpend: 0,
    isActive: true,
  },
  {
    id: 'coup-02',
    code: 'MEGA80',
    discountPercentage: 30,
    minSpend: 299,
    isActive: true,
  },
  {
    id: 'coup-03',
    code: 'FLAT149',
    discountPercentage: 15,
    minSpend: 0,
    isActive: true,
  },
];

export const INITIAL_SETTINGS: StoreSettings = {
  announcementText: '⚡ Flash Sale: Flat ₹149 / $1.99 Deals Today Only! Use code CREATOR70 for extra 20% OFF',
  announcementActive: true,
  countdownActive: true,
  countdownTargetHours: 14,
  globalDiscountTag: 'UP TO 90% OFF',
  supportEmail: 'support@apexdigital.store',
  currencyRates: {
    INR: 1,
    USD: 0.012, // ₹100 ~ $1.20
    EUR: 0.011,
  },
};

export const INITIAL_ORDERS: Order[] = [
  {
    id: 'ORD-8941',
    customerName: 'Alex Rivera',
    customerEmail: 'alex.rivera@creatorspace.io',
    items: [
      {
        productId: 'prod-cc-01',
        name: 'Ultimate Content Creator Mega Vault (5,000+ Assets)',
        salePrice: 199,
        quantity: 1,
        deliveryLink: 'https://drive.google.com/drive/folders/content-creator-vault-instant-access',
      },
    ],
    subtotal: 199,
    discountAmount: 40,
    total: 159,
    appliedCoupon: 'CREATOR70',
    currency: 'INR',
    paymentMethod: 'UPI / GPay',
    status: 'DELIVERED',
    createdAt: '2026-10-07T14:32:00.000Z',
  },
  {
    id: 'ORD-8940',
    customerName: 'Sarah Jenkins',
    customerEmail: 'sarah.design@agencyco.com',
    items: [
      {
        productId: 'prod-gd-01',
        name: 'Master Graphic Designer Suite (10,000+ Vector & PSD Assets)',
        salePrice: 249,
        quantity: 1,
        deliveryLink: 'https://mega.nz/folder/graphic-design-master-suite-cloud',
      },
      {
        productId: 'prod-em-01',
        name: 'Email Marketing Mega Bundle (1,200+ High-Conversion Sequences)',
        salePrice: 149,
        quantity: 1,
        deliveryLink: 'https://drive.google.com/drive/folders/email-marketing-mega-vault',
      },
    ],
    subtotal: 398,
    discountAmount: 119,
    total: 279,
    appliedCoupon: 'MEGA80',
    currency: 'INR',
    paymentMethod: 'Credit/Debit Card',
    status: 'DELIVERED',
    createdAt: '2026-10-07T12:15:00.000Z',
  },
  {
    id: 'ORD-8939',
    customerName: 'Vikram Mehta',
    customerEmail: 'vikram.m@techbuild.dev',
    items: [
      {
        productId: 'prod-sw-01',
        name: 'Full-Stack Developer Toolkit & Next.js SaaS Boilerplates',
        salePrice: 299,
        quantity: 1,
        deliveryLink: 'https://drive.google.com/drive/folders/fullstack-developer-saas-vault',
      },
    ],
    subtotal: 299,
    discountAmount: 0,
    total: 299,
    currency: 'INR',
    paymentMethod: 'UPI / GPay',
    status: 'DELIVERED',
    createdAt: '2026-10-07T09:40:00.000Z',
  },
];
