import { Product, Coupon, StoreSettings, Order } from './types';

export const SAMPLE_IMAGE_PRESETS = [
  {
    title: '4K Cinema Video & Media Production',
    url: 'https://images.unsplash.com/photo-1574717024653-61fd2cf4d44d?auto=format&fit=crop&w=900&q=80',
    category: 'CONTENT CREATION & MEDIA ASSETS',
  },
  {
    title: 'Creator Desk & Content Matrix Workspace',
    url: 'https://images.unsplash.com/photo-1517245386807-bb43f82c33c4?auto=format&fit=crop&w=900&q=80',
    category: 'CONTENT CREATION & MEDIA ASSETS',
  },
  {
    title: 'Brand Identity Mockups & Typography Suite',
    url: 'https://images.unsplash.com/photo-1626785774573-4b799315345d?auto=format&fit=crop&w=900&q=80',
    category: 'GRAPHIC DESIGN & CREATIVE TEMPLATES',
  },
  {
    title: 'UI/UX Design System & Figma Wireframes',
    url: 'https://images.unsplash.com/photo-1581291518655-9523c932deb4?auto=format&fit=crop&w=900&q=80',
    category: 'GRAPHIC DESIGN & CREATIVE TEMPLATES',
  },
  {
    title: 'Agency Scale Funnels & Analytics OS',
    url: 'https://images.unsplash.com/photo-1460925895917-afdab827c52f?auto=format&fit=crop&w=900&q=80',
    category: 'BUSINESS & DIGITAL MARKETING RESOURCES',
  },
  {
    title: 'E-Commerce Growth Playbook & Creatives',
    url: 'https://images.unsplash.com/photo-1556742049-0a67c5574f73?auto=format&fit=crop&w=900&q=80',
    category: 'BUSINESS & DIGITAL MARKETING RESOURCES',
  },
  {
    title: 'Email Marketing & High-Converting Sequences',
    url: 'https://images.unsplash.com/photo-1563986768609-322da13575f3?auto=format&fit=crop&w=900&q=80',
    category: 'EMAIL MARKETING MEGA BUNDLE',
  },
  {
    title: 'Newsletter Monetization & Sponsor Pitch Kit',
    url: 'https://images.unsplash.com/photo-1557804506-669a67965ba0?auto=format&fit=crop&w=900&q=80',
    category: 'EMAIL MARKETING MEGA BUNDLE',
  },
  {
    title: 'Full-Stack Next.js Developer SaaS Boilerplate',
    url: 'https://images.unsplash.com/photo-1555066931-4365d14bab8c?auto=format&fit=crop&w=900&q=80',
    category: 'SOFTWARE, WORDPRESS & DEVELOPMENT TOOLS',
  },
  {
    title: 'WordPress Power Pro Suite & Web Kits',
    url: 'https://images.unsplash.com/photo-1507238691740-187a5b1d37b8?auto=format&fit=crop&w=900&q=80',
    category: 'SOFTWARE, WORDPRESS & DEVELOPMENT TOOLS',
  },
  {
    title: 'Cinematic Filmmaking Gear & 3D LUTs',
    url: 'https://images.unsplash.com/photo-1492691527719-9d1e07e534b4?auto=format&fit=crop&w=900&q=80',
    category: 'VIDEO & AUDIO PRODUCTION BUNDLE',
  },
  {
    title: 'Podcast & Audio Studio Vocal Mastering',
    url: 'https://images.unsplash.com/photo-1590602847861-f357a9332bbc?auto=format&fit=crop&w=900&q=80',
    category: 'VIDEO & AUDIO PRODUCTION BUNDLE',
  },
  {
    title: 'Solopreneur Digital Wealth Blueprint',
    url: 'https://images.unsplash.com/photo-1522202176988-66273c2fd55f?auto=format&fit=crop&w=900&q=80',
    category: 'COURSES & EDUCATIONAL RESOURCES',
  },
  {
    title: 'AI Automation & Prompt Engineering Vault',
    url: 'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?auto=format&fit=crop&w=900&q=80',
    category: 'COURSES & EDUCATIONAL RESOURCES',
  },
  {
    title: 'Studio Microphone & Podcast Audio Kit',
    url: 'https://images.unsplash.com/photo-1598488035139-bdbb2231ce04?auto=format&fit=crop&w=900&q=80',
    category: 'CONTENT CREATION & MEDIA ASSETS',
  },
  {
    title: 'Minimalist Vector Icon & Typography System',
    url: 'https://images.unsplash.com/photo-1507238691740-187a5b1d37b8?auto=format&fit=crop&w=900&q=80',
    category: 'GRAPHIC DESIGN & CREATIVE TEMPLATES',
  },
  {
    title: 'Digital Marketing Analytics & Conversion Dashboard',
    url: 'https://images.unsplash.com/photo-1551836022-d5d88e9218df?auto=format&fit=crop&w=900&q=80',
    category: 'BUSINESS & DIGITAL MARKETING RESOURCES',
  },
  {
    title: 'Email Copywriting & Inbox Sequencing Kit',
    url: 'https://images.unsplash.com/photo-1596526131083-e8c633c948d2?auto=format&fit=crop&w=900&q=80',
    category: 'EMAIL MARKETING MEGA BUNDLE',
  },
  {
    title: 'Modern Cloud Architecture & Dev Tools',
    url: 'https://images.unsplash.com/photo-1517694712202-14dd9538aa97?auto=format&fit=crop&w=900&q=80',
    category: 'SOFTWARE, WORDPRESS & DEVELOPMENT TOOLS',
  },
  {
    title: 'Cinematic 8K Drone & Video Color Presets',
    url: 'https://images.unsplash.com/photo-1536240478700-b869070f9279?auto=format&fit=crop&w=900&q=80',
    category: 'VIDEO & AUDIO PRODUCTION BUNDLE',
  },
  {
    title: 'Online Video Masterclass & Academy Vault',
    url: 'https://images.unsplash.com/photo-1516321318423-f06f85e504b3?auto=format&fit=crop&w=900&q=80',
    category: 'COURSES & EDUCATIONAL RESOURCES',
  },
];

export const INITIAL_PRODUCTS: Product[] = [
  // 1. CONTENT CREATION & MEDIA ASSETS
  {
    id: 'prod-cc-01',
    name: 'Ultimate Content Creator Mega Vault (5,000+ Assets)',
    slug: 'ultimate-content-creator-mega-vault',
    category: 'CONTENT CREATION & MEDIA ASSETS',
    description: 'The master content bundle packed with 5,000+ viral Reels & Shorts templates, 4K kinetic typography clips, motion graphics hooks, YouTube thumbnail PSDs, sound FX, and ready-to-post vertical videos.',
    features: [
      '2,500+ Ready-to-edit Canva & Premiere Reels/Shorts templates',
      '800+ 4K Cinematic Background Loops & Textures',
      '1,200+ Sound Effects (Whooshes, Risers, Pop, Bass Drops)',
      '150+ High-CTR YouTube Thumbnail Templates (PSD & Canva)',
      'Commercial License & Lifetime Free Updates',
    ],
    regularPrice: 2499,
    salePrice: 199,
    badges: ['BESTSELLER', 'MEGA BUNDLE', '85% OFF'],
    deliveryLink: 'https://drive.google.com/drive/folders/content-creator-vault-instant-access',
    fileSize: '48.5 GB',
    fileFormat: 'Canva / Premiere / PSD / 4K MP4',
    rating: 4.9,
    reviewCount: 482,
    salesCount: 3240,
    mockupTheme: 'amber',
    imageUrl: 'https://images.unsplash.com/photo-1574717024653-61fd2cf4d44d?auto=format&fit=crop&w=900&q=80',
    isFeatured: true,
    isActive: true,
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'prod-cc-02',
    name: 'Viral Hooks, Scripts & Notion Content Engine',
    slug: 'viral-hooks-scripts-notion-engine',
    category: 'CONTENT CREATION & MEDIA ASSETS',
    description: 'Over 1,000 battle-tested viral hooks, storytelling frameworks, 30-day content calendar templates, and complete Notion workspace for creators and agencies.',
    features: [
      '1,000+ Proven video hook formulas across 12 niches',
      'Full Notion Creator OS & Content Matrix Dashboard',
      'Script breakdown templates for TikTok, Reels, & YouTube',
      'Carousel design templates for LinkedIn & Instagram',
    ],
    regularPrice: 1499,
    salePrice: 149,
    badges: ['HOT DEAL', '70% OFF'],
    deliveryLink: 'https://drive.google.com/drive/folders/notion-creator-engine-access',
    fileSize: '2.4 GB',
    fileFormat: 'Notion Template / PDF / DOCX',
    rating: 4.8,
    reviewCount: 194,
    salesCount: 1420,
    mockupTheme: 'obsidian',
    imageUrl: 'https://images.unsplash.com/photo-1517245386807-bb43f82c33c4?auto=format&fit=crop&w=900&q=80',
    isActive: true,
    updatedAt: new Date().toISOString(),
  },

  // 2. GRAPHIC DESIGN & CREATIVE TEMPLATES
  {
    id: 'prod-gd-01',
    name: 'Master Graphic Designer Suite (10,000+ Vector & PSD Assets)',
    slug: 'master-graphic-designer-suite',
    category: 'GRAPHIC DESIGN & CREATIVE TEMPLATES',
    description: 'Gigantic creative bundle containing premium branding mockups, geometric vector icons, typography posters, social media layout kits, Lightroom presets, and textures.',
    features: [
      '500+ High-Resolution Photorealistic Mockups (300 DPI, Smart Objects)',
      '3,000+ Vector Icons, Badges & Vintage Emblem illustrations',
      '1,500+ Premium Fonts & Editorial Typography Pairings',
      '50+ Complete Brand Identity Presentation Decks',
      'Full Commercial & Print-on-Demand License',
    ],
    regularPrice: 3999,
    salePrice: 249,
    badges: ['BESTSELLER', 'HOT SELL'],
    deliveryLink: 'https://mega.nz/folder/graphic-design-master-suite-cloud',
    fileSize: '62.0 GB',
    fileFormat: 'PSD / AI / EPS / OTF / SVG',
    rating: 5.0,
    reviewCount: 521,
    salesCount: 2980,
    mockupTheme: 'purple',
    imageUrl: 'https://images.unsplash.com/photo-1626785774573-4b799315345d?auto=format&fit=crop&w=900&q=80',
    isFeatured: true,
    isActive: true,
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'prod-gd-02',
    name: 'Ultra UI/UX Design System & Figma Wireframe Kit',
    slug: 'ultra-ui-ux-design-system-figma-kit',
    category: 'GRAPHIC DESIGN & CREATIVE TEMPLATES',
    description: 'Enterprise Figma design system with 2,400+ auto-layout components, WCAG accessible color palettes, responsive web wireframes, and mobile app screens.',
    features: [
      '2,400+ Auto-Layout 5.0 Figma UI components',
      '60+ Pre-built Responsive Web & Dashboard Layouts',
      'Design token library with light & dark mode variants',
      'Interactive prototype states & micro-interactions',
    ],
    regularPrice: 2999,
    salePrice: 199,
    badges: ['LIMITED OFFER'],
    deliveryLink: 'https://drive.google.com/drive/folders/figma-ui-system-enterprise',
    fileSize: '1.8 GB',
    fileFormat: 'Figma (.fig) / Tokens JSON',
    rating: 4.9,
    reviewCount: 284,
    salesCount: 1650,
    mockupTheme: 'cyan',
    imageUrl: 'https://images.unsplash.com/photo-1581291518655-9523c932deb4?auto=format&fit=crop&w=900&q=80',
    isActive: true,
    updatedAt: new Date().toISOString(),
  },

  // 3. BUSINESS & DIGITAL MARKETING RESOURCES
  {
    id: 'prod-bm-01',
    name: 'Agency Scale In A Box: Business & Funnel OS',
    slug: 'agency-scale-business-funnel-os',
    category: 'BUSINESS & DIGITAL MARKETING RESOURCES',
    description: 'Complete operating system for digital agencies and freelancers. Includes high-converting proposal templates, client contracts, SOPs, pitch decks, and ad swipe files.',
    features: [
      'Legally vetted client service agreements & NDAs',
      'High-converting pitch decks (Keynote, PowerPoint, Google Slides)',
      '30+ Standard Operating Procedures (SOPs) for team delegation',
      'Meta & Google Ads high-ROI swipe files with $2M+ spend data',
      'Client onboarding Notion portal & project tracker',
    ],
    regularPrice: 3499,
    salePrice: 249,
    badges: ['HOT DEAL', 'BESTSELLER'],
    deliveryLink: 'https://drive.google.com/drive/folders/agency-scale-in-a-box-bundle',
    fileSize: '4.8 GB',
    fileFormat: 'Notion / PPTX / PDF / DOCX',
    rating: 4.9,
    reviewCount: 310,
    salesCount: 2150,
    mockupTheme: 'emerald',
    imageUrl: 'https://images.unsplash.com/photo-1460925895917-afdab827c52f?auto=format&fit=crop&w=900&q=80',
    isFeatured: true,
    isActive: true,
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'prod-bm-02',
    name: 'SaaS & E-Commerce Growth Playbook + Ad Creatives',
    slug: 'saas-ecommerce-growth-playbook',
    category: 'BUSINESS & DIGITAL MARKETING RESOURCES',
    description: 'Step-by-step conversion rate optimization (CRO) audits, landing page blueprints, and 200+ tested ad creative PSD templates for scaling e-commerce brands.',
    features: [
      '200+ E-Commerce Ad Creatives (Statics, Carousels, Stories)',
      'High-converting Shopify & WooCommerce product page wireframes',
      'Retention & LTV maximization playbook',
      'Influencer outreach email templates & tracker sheet',
    ],
    regularPrice: 1999,
    salePrice: 149,
    badges: ['70% OFF'],
    deliveryLink: 'https://mega.nz/folder/ecommerce-growth-playbook-direct',
    fileSize: '3.6 GB',
    fileFormat: 'PSD / XLSX / PDF',
    rating: 4.8,
    reviewCount: 142,
    salesCount: 980,
    mockupTheme: 'rose',
    imageUrl: 'https://images.unsplash.com/photo-1556742049-0a67c5574f73?auto=format&fit=crop&w=900&q=80',
    isActive: true,
    updatedAt: new Date().toISOString(),
  },

  // 4. EMAIL MARKETING MEGA BUNDLE
  {
    id: 'prod-em-01',
    name: 'Email Marketing Mega Bundle (1,200+ High-Conversion Sequences)',
    slug: 'email-marketing-mega-bundle',
    category: 'EMAIL MARKETING MEGA BUNDLE',
    description: 'The ultimate copywriting vault: Welcome series, abandoned cart flows, black friday flash sales, product launch campaigns, and cold outreach B2B sequences.',
    features: [
      '1,200+ Copywritten email templates tested with 40%+ open rates',
      '8 complete automated Klaviyo & Mailchimp drip workflows',
      '500+ Attention-grabbing subject line generators',
      'HTML email design templates with 100% mobile responsiveness',
      'B2B cold email lead generation sequences with follow-ups',
    ],
    regularPrice: 2499,
    salePrice: 149,
    badges: ['MEGA BUNDLE', 'HOT SELL', 'FLASH SALE'],
    deliveryLink: 'https://drive.google.com/drive/folders/email-marketing-mega-vault',
    fileSize: '3.1 GB',
    fileFormat: 'HTML / DOCX / Klaviyo Flows / PDF',
    rating: 4.9,
    reviewCount: 415,
    salesCount: 2890,
    mockupTheme: 'amber',
    imageUrl: 'https://images.unsplash.com/photo-1563986768609-322da13575f3?auto=format&fit=crop&w=900&q=80',
    isFeatured: true,
    isActive: true,
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'prod-em-02',
    name: 'Newsletter Monetization & Sponsor Pitch Kit',
    slug: 'newsletter-monetization-sponsor-kit',
    category: 'EMAIL MARKETING MEGA BUNDLE',
    description: 'Grow your Substack or Beehiiv newsletter from 0 to 50k subscribers. Complete media kit deck, sponsorship rate card, and cold pitch templates.',
    features: [
      'Editable Figma & Canva media kit templates for sponsors',
      'Sponsor email outreach sequences with contract templates',
      'Newsletter referral program setup blueprints',
      'Beehiiv & Substack layout styling templates',
    ],
    regularPrice: 1499,
    salePrice: 149,
    badges: ['LIMITED OFFER'],
    deliveryLink: 'https://mega.nz/folder/newsletter-growth-sponsor-kit',
    fileSize: '1.2 GB',
    fileFormat: 'Canva / Figma / PDF',
    rating: 4.7,
    reviewCount: 98,
    salesCount: 650,
    mockupTheme: 'cyan',
    imageUrl: 'https://images.unsplash.com/photo-1557804506-669a67965ba0?auto=format&fit=crop&w=900&q=80',
    isActive: true,
    updatedAt: new Date().toISOString(),
  },

  // 5. SOFTWARE, WORDPRESS & DEVELOPMENT TOOLS
  {
    id: 'prod-sw-01',
    name: 'Full-Stack Developer Toolkit & Next.js SaaS Boilerplates',
    slug: 'fullstack-dev-toolkit-nextjs-saas',
    category: 'SOFTWARE, WORDPRESS & DEVELOPMENT TOOLS',
    description: 'Production-ready Next.js 15, Tailwind v4, React 19 SaaS starter repositories with Stripe auth, database schemas, API wrappers, and 80+ prebuilt UI components.',
    features: [
      '3 Production-ready Next.js SaaS Starter boilerplates (App Router)',
      'Pre-configured Auth, Stripe Billing, and PostgreSQL schemas',
      '80+ Custom interactive Tailwind UI components',
      'Docker Compose environments & CI/CD deployment scripts',
      'Comprehensive developer documentation & lifetime updates',
    ],
    regularPrice: 4999,
    salePrice: 299,
    badges: ['BESTSELLER', 'HOT DEAL'],
    deliveryLink: 'https://drive.google.com/drive/folders/fullstack-developer-saas-vault',
    fileSize: '8.5 GB',
    fileFormat: 'Git Repos / TypeScript / Docker / ZIP',
    rating: 5.0,
    reviewCount: 389,
    salesCount: 2410,
    mockupTheme: 'cyan',
    imageUrl: 'https://images.unsplash.com/photo-1555066931-4365d14bab8c?auto=format&fit=crop&w=900&q=80',
    isFeatured: true,
    isActive: true,
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'prod-sw-02',
    name: 'WordPress Power Pro Suite (Themes, Plugins & Elementor Kits)',
    slug: 'wordpress-power-pro-suite',
    category: 'SOFTWARE, WORDPRESS & DEVELOPMENT TOOLS',
    description: '150+ Premium WordPress landing page templates, Elementor Pro wireframes, WooCommerce speed-optimization scripts, and SEO schema presets.',
    features: [
      '150+ Niche-specific Elementor & Gutenberg page templates',
      'High-speed WooCommerce checkout funnels',
      'Technical SEO audit checklist & RankMath/Yoast configurations',
      'Custom CSS/JS snippets for header animations and popups',
    ],
    regularPrice: 2999,
    salePrice: 199,
    badges: ['70% OFF'],
    deliveryLink: 'https://mega.nz/folder/wordpress-power-pro-suite-cloud',
    fileSize: '14.2 GB',
    fileFormat: 'JSON / Elementor Kits / ZIP',
    rating: 4.8,
    reviewCount: 230,
    salesCount: 1540,
    mockupTheme: 'obsidian',
    imageUrl: 'https://images.unsplash.com/photo-1507238691740-187a5b1d37b8?auto=format&fit=crop&w=900&q=80',
    isActive: true,
    updatedAt: new Date().toISOString(),
  },

  // 6. VIDEO & AUDIO PRODUCTION BUNDLE
  {
    id: 'prod-va-01',
    name: 'Cinematic Filmmaker & Audio Production Mega Vault',
    slug: 'cinematic-filmmaker-audio-production-vault',
    category: 'VIDEO & AUDIO PRODUCTION BUNDLE',
    description: 'Hollywood-grade post-production library: 450+ 3D LUTs (Rec.709, LOG, Sony, Arri), 8K film grain overlays, seamless transition presets, and 3,000+ lossless SFX.',
    features: [
      '450+ Cinematic LUTs for Premiere, DaVinci Resolve, FCPX, CapCut',
      '8K Real 35mm & 16mm Film Grain, Light Leaks & Dust Overlays',
      '3,000+ Lossless WAV Sound Effects (Trailer Hits, Ambient, Foley)',
      'Smooth Speed Ramp & Zoom Transitions for Premiere Pro',
      'Royalty-Free for Commercial YouTube & Broadcast TV',
    ],
    regularPrice: 3999,
    salePrice: 249,
    badges: ['MEGA BUNDLE', 'BESTSELLER', 'HOT DEAL'],
    deliveryLink: 'https://drive.google.com/drive/folders/filmmaker-cinematic-audio-vault',
    fileSize: '54.0 GB',
    fileFormat: 'CUBE / PRPROJ / 4K ProRes / 24-bit WAV',
    rating: 4.9,
    reviewCount: 476,
    salesCount: 3120,
    mockupTheme: 'rose',
    imageUrl: 'https://images.unsplash.com/photo-1492691527719-9d1e07e534b4?auto=format&fit=crop&w=900&q=80',
    isFeatured: true,
    isActive: true,
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'prod-va-02',
    name: 'Podcast & Voiceover Mastering Suite',
    slug: 'podcast-voiceover-mastering-suite',
    category: 'VIDEO & AUDIO PRODUCTION BUNDLE',
    description: 'One-click vocal mastering presets for Audacity, Adobe Audition, Logic Pro, and DaVinci Fairlight. Turn amateur bedroom audio into crisp studio broadcasts.',
    features: [
      '12 Vocal Warmth & De-essing chains for dynamic microphones',
      'Podcast intro/outro royalty-free music stems',
      'Room echo reduction guide and EQ presets',
      'Loudness standardizer presets (-16 LUFS broadcast compliant)',
    ],
    regularPrice: 1999,
    salePrice: 149,
    badges: ['LIMITED OFFER'],
    deliveryLink: 'https://mega.nz/folder/podcast-audio-mastering-suite',
    fileSize: '6.4 GB',
    fileFormat: 'Audio Presets / WAV / PDF',
    rating: 4.8,
    reviewCount: 167,
    salesCount: 890,
    mockupTheme: 'purple',
    imageUrl: 'https://images.unsplash.com/photo-1590602847861-f357a9332bbc?auto=format&fit=crop&w=900&q=80',
    isActive: true,
    updatedAt: new Date().toISOString(),
  },

  // 7. COURSES & EDUCATIONAL RESOURCES
  {
    id: 'prod-ce-01',
    name: 'Digital Wealth & Solopreneur Blueprint (10 In-Depth Modules)',
    slug: 'digital-wealth-solopreneur-blueprint',
    category: 'COURSES & EDUCATIONAL RESOURCES',
    description: 'Comprehensive curriculum on building, launching, and automating profitable digital products, digital agencies, and creator businesses from scratch.',
    features: [
      '10 High-definition video masterclass modules with transcripts',
      'Plug-and-play sales page wireframes with 12% conversion rates',
      'Customer acquisition frameworks (Organic SEO, X, TikTok, Ads)',
      'Automation blueprints for Zapier, Gumroad, and Stripe checkout',
      'Private resource library & checklist spreadsheets',
    ],
    regularPrice: 4499,
    salePrice: 299,
    badges: ['BESTSELLER', 'HOT SELL'],
    deliveryLink: 'https://drive.google.com/drive/folders/solopreneur-digital-wealth-blueprint',
    fileSize: '22.8 GB',
    fileFormat: '1080p MP4 / PDF / Notion Portal',
    rating: 4.9,
    reviewCount: 388,
    salesCount: 2750,
    mockupTheme: 'emerald',
    imageUrl: 'https://images.unsplash.com/photo-1522202176988-66273c2fd55f?auto=format&fit=crop&w=900&q=80',
    isFeatured: true,
    isActive: true,
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'prod-ce-02',
    name: 'AI Automation & Prompt Engineering Mastery Library',
    slug: 'ai-automation-prompt-engineering-mastery',
    category: 'COURSES & EDUCATIONAL RESOURCES',
    description: '3,000+ production-ready prompts, custom GPT build blueprints, Make/n8n automation workflows, and actionable business use case tutorials.',
    features: [
      '3,000+ Categorized prompts for Copywriting, Coding, SEO & Sales',
      '15 Ready-to-import n8n & Make.com AI workflow blueprints',
      'Complete guide to fine-tuning and retrieval-augmented generation (RAG)',
      'Cheatsheets for Gemini, Claude, and GPT-4o prompting architectures',
    ],
    regularPrice: 2499,
    salePrice: 149,
    badges: ['HOT DEAL', 'FLASH SALE'],
    deliveryLink: 'https://drive.google.com/drive/folders/ai-automation-prompt-mastery',
    fileSize: '4.5 GB',
    fileFormat: 'JSON / PDF / Notion / Markdown',
    rating: 5.0,
    reviewCount: 295,
    salesCount: 2190,
    mockupTheme: 'amber',
    imageUrl: 'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?auto=format&fit=crop&w=900&q=80',
    isActive: true,
    updatedAt: new Date().toISOString(),
  },
];

export const INITIAL_COUPONS: Coupon[] = [
  {
    id: 'coup-01',
    code: 'CREATOR70',
    discountPercentage: 20,
    minSpend: 0,
    isActive: true,
  },
  {
    id: 'coup-02',
    code: 'MEGA80',
    discountPercentage: 30,
    minSpend: 299,
    isActive: true,
  },
  {
    id: 'coup-03',
    code: 'FLAT149',
    discountPercentage: 15,
    minSpend: 0,
    isActive: true,
  },
];

export const INITIAL_SETTINGS: StoreSettings = {
  announcementText: '⚡ Flash Sale: Flat ₹149 / $1.99 Deals Today Only! Use code CREATOR70 for extra 20% OFF',
  announcementActive: true,
  countdownActive: true,
  countdownTargetHours: 14,
  globalDiscountTag: 'UP TO 90% OFF',
  supportEmail: 'support@apexdigital.store',
  currencyRates: {
    INR: 1,
    USD: 0.012, // ₹100 ~ $1.20
    EUR: 0.011,
  },
};

export const INITIAL_ORDERS: Order[] = [
  {
    id: 'ORD-8941',
    customerName: 'Alex Rivera',
    customerEmail: 'alex.rivera@creatorspace.io',
    items: [
      {
        productId: 'prod-cc-01',
        name: 'Ultimate Content Creator Mega Vault (5,000+ Assets)',
        salePrice: 199,
        quantity: 1,
        deliveryLink: 'https://drive.google.com/drive/folders/content-creator-vault-instant-access',
      },
    ],
    subtotal: 199,
    discountAmount: 40,
    total: 159,
    appliedCoupon: 'CREATOR70',
    currency: 'INR',
    paymentMethod: 'UPI / GPay',
    status: 'DELIVERED',
    createdAt: '2026-10-07T14:32:00.000Z',
  },
  {
    id: 'ORD-8940',
    customerName: 'Sarah Jenkins',
    customerEmail: 'sarah.design@agencyco.com',
    items: [
      {
        productId: 'prod-gd-01',
        name: 'Master Graphic Designer Suite (10,000+ Vector & PSD Assets)',
        salePrice: 249,
        quantity: 1,
        deliveryLink: 'https://mega.nz/folder/graphic-design-master-suite-cloud',
      },
      {
        productId: 'prod-em-01',
        name: 'Email Marketing Mega Bundle (1,200+ High-Conversion Sequences)',
        salePrice: 149,
        quantity: 1,
        deliveryLink: 'https://drive.google.com/drive/folders/email-marketing-mega-vault',
      },
    ],
    subtotal: 398,
    discountAmount: 119,
    total: 279,
    appliedCoupon: 'MEGA80',
    currency: 'INR',
    paymentMethod: 'Credit/Debit Card',
    status: 'DELIVERED',
    createdAt: '2026-10-07T12:15:00.000Z',
  },
  {
    id: 'ORD-8939',
    customerName: 'Vikram Mehta',
    customerEmail: 'vikram.m@techbuild.dev',
    items: [
      {
        productId: 'prod-sw-01',
        name: 'Full-Stack Developer Toolkit & Next.js SaaS Boilerplates',
        salePrice: 299,
        quantity: 1,
        deliveryLink: 'https://drive.google.com/drive/folders/fullstack-developer-saas-vault',
      },
    ],
    subtotal: 299,
    discountAmount: 0,
    total: 299,
    currency: 'INR',
    paymentMethod: 'UPI / GPay',
    status: 'DELIVERED',
    createdAt: '2026-10-07T09:40:00.000Z',
  },
];
